#!/bin/sh
### BEGIN INIT INFO
# Provides: configure_ufw
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: block all outgoing traffic
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Start blocking outgoing traffic"
    deny_default_out.sh &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
